// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAMwNaWiPSY4MjRmn-KMKtw7SMkvgXPWk',
    appId: '1:166608569982:web:40e3a3e376c076ea0f3a2f',
    messagingSenderId: '166608569982',
    projectId: 'store-app-46e69',
    authDomain: 'store-app-46e69.firebaseapp.com',
    storageBucket: 'store-app-46e69.firebasestorage.app',
    measurementId: 'G-HYSXC9FN2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFe-R5rGdctLQHNOMZjANU1oNdQ_7zbu0',
    appId: '1:166608569982:android:d1df98438428a4250f3a2f',
    messagingSenderId: '166608569982',
    projectId: 'store-app-46e69',
    storageBucket: 'store-app-46e69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACKnXNKDcnIJB1JEoSk_Vyl4r1D3nA6yY',
    appId: '1:166608569982:ios:b1961bb4794576590f3a2f',
    messagingSenderId: '166608569982',
    projectId: 'store-app-46e69',
    storageBucket: 'store-app-46e69.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACKnXNKDcnIJB1JEoSk_Vyl4r1D3nA6yY',
    appId: '1:166608569982:ios:b1961bb4794576590f3a2f',
    messagingSenderId: '166608569982',
    projectId: 'store-app-46e69',
    storageBucket: 'store-app-46e69.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAMwNaWiPSY4MjRmn-KMKtw7SMkvgXPWk',
    appId: '1:166608569982:web:879dc60066b4a6c90f3a2f',
    messagingSenderId: '166608569982',
    projectId: 'store-app-46e69',
    authDomain: 'store-app-46e69.firebaseapp.com',
    storageBucket: 'store-app-46e69.firebasestorage.app',
    measurementId: 'G-7LL3H3QYKV',
  );
}
